name: ticket_api
publish_to: "none"

environment:
  sdk: ^3.4.3

dependencies:
  dio: ^5.5.0+1
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0
  retrofit: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.4
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.1
  yumemi_lints: ^2.1.0
