name: ticket_database
publish_to: "none"

environment:
  sdk: ^3.4.3

dependencies:
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.4
  json_serializable: ^6.8.0
  yumemi_lints: ^2.1.0
