name: ticket_app
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ^3.22.2

dependencies:
  dio: ^5.5.0+1
  envied: ^0.5.4+1
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  hooks_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  supabase_auth_ui: ^0.5.0
  supabase_flutter: ^2.5.7
  ticket_api:
    path: ../packages/ticket_api
  ticket_database:
    path: ../packages/ticket_database
  url_launcher: ^6.3.0
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.5.11
  envied_generator: ^0.5.4+1
  go_router_builder: ^2.7.0
  riverpod_generator: ^3.0.0-dev.3
  riverpod_lint: ^3.0.0-dev.3
  yumemi_lints: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - path: assets/svgs/
