name: ticket_app
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ^3.22.2

dependencies:
  dio: ^5.5.0+1
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_web_plugins:
    sdk: flutter
  go_router: ^14.2.0
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  supabase_auth_ui: ^0.5.0
  supabase_flutter: ^2.5.7
  ticket_api:
    path: ../packages/ticket_api
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  envied_generator: ^0.5.4+1
  go_router_builder: ^2.7.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  yumemi_lints: ^2.1.0

flutter:
  uses-material-design: true
